bettercode-oss/better-ADMIN

- src/components/AppLayout.js
> #2 사용하지 않는 parameter 정리

- package.json
- src/App.js
- src/components/AppLayout.js
- src/index.css
- src/pages/Home.js
- src/pages/Home.module.css
Dashboard summury 추가
Home.module.css 추가 (PostCSS 적용)
Graph component는 추후 추가
SNB5 check 해주세요. <-- 이 쪽 페이지에서만 dashboard가 같이 뜹니다. 왜 그런지 모르겠어요.
> #13 Dashboard 제작

- src/App.js
- src/auth/auth.service.js
- src/components/AppLayout.js
- src/components/AuthRoute.js
- src/components/Login.js
- src/components/LoginInfo.js
- src/config/admin.config.js
- src/config/axios.config.js
- src/config/navigation.config.js
- src/index.js
@yoonjong-park 자세한 내용은 https://velog.io/@yaytomato/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%90%EC%84%9C-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0 을 참조하세요.
> #10 보다 안전한 로그인 처리 구현

- src/components/AppLayout.js
- src/config/admin.config.js
- src/pages/Sub2.js
> #18 Layout Content 영역이 화면을 영역을 넘어가는 경우 레이아웃 깨짐 오류

- src/components/AppLayout.js
> #20 Layout Content 영역이 화면을 영역을 넘어가 확장되는 경우 사이드 바는 확장되지 않는 오류

- package.json
- src/App.js
- src/components/PageRouting.js
- src/components/router/AuthRoute.js
- src/components/router/PageRoute.js
- src/components/settings/access-control/PermissionList.js
- src/components/settings/access-control/RoleList.js
- src/components/settings/member/MemberList.js
> #24 로딩시 상단바로 페이지 로딩 진행율 보여 주기

- src/App.js
- src/components/AppLayout.js
- src/config/admin.config.js
- src/config/axios.configur.js
- src/index.js
> #22 네트워크가 끊겼을 때 알람 표시하기

- package.json
- src/components/Login.js
- src/components/MemberSignUp.js
- src/components/settings/app.settings.navigation.config.js
- src/components/settings/member/MemberApproval.js
- src/components/settings/member/member.service.js
- src/pages/Home.js
> #31 사용자가 betterADMIN 사용을 위해 멤버로 신청하고 관리자가 승인한 멤버가 로그인할 수 있게 만든다.

- src/components/AppLayout.js
> #35 화면 새로 고침 후 GNB 영역 오류

- src/components/Login.js
- src/config/admin.config.js
- src/config/axios.configur.js
- src/index.js
> #37 브라우저를 새로 고침할 때 showLoading 함수 동작하지 않음

- src/components/settings/access-control/access.control.service.js
- src/components/settings/member/MemberApproval.js
- src/components/settings/member/MemberList.js
- src/components/settings/member/member.service.js
- src/components/settings/organization/OrganizationMemberChange.js
> #48 조직도에 멤버 연결 시 승인 되지 않는 멤버가 노출됨

- src/config/axios.configur.js
> #53 화면에서 better ADMIN 백엔드가 아닌 다른 서버의 API 호출 시 CORS 문제

- src/components/AppLayout.js
> #43 사이드 메뉴 최소화 후 클릭 시 Sub 메뉴가 사라지지 않음

- package.json
- src/App.js
- src/components/Login.js
- src/components/router/AuthRoute.js
> #56 로그인 하지 않는 상태에서 어드민 URL 을 입력하면 로그인 화면으로 가고 로그인 후에 입력한 URL로 이동하게 하기

- src/components/AppLayout.js
> #30 화면 히스토리를 탭 UI 적용해 보기

- src/components/AppLayout.js
> #59 현재 활성화 된 화면 히스토리 탭에서 다른 탭을 지웠을 때 탭이 이동되는 오류

- package.json
- src/components/layout/AppLayoutContext.js
- src/components/layout/Content.js
- src/components/layout/Header.js
- src/components/layout/NavigationIcon.js
- src/components/layout/Sider.js
- src/components/login/Login.js
- src/config/navigation.config.js
- src/config/navigation.json
> #61 네비게이션 아이콘에 React Icons 지원하기

- src/components/settings/member/MemberList.js
- src/components/settings/organization/OrganizationMemberChange.js
> #81 멤버가 동명이인을 고려하여 이름 옆에 식별할 수 있는 id 나 이메일을 함께 보여 준다.

- src/App.js
- src/auth/auth.service.js
- src/auth/member.context.js
- src/components/settings/AppSettings.js
- src/components/settings/access-control/PermissionList.js
- src/components/settings/access-control/RoleList.js
- src/components/settings/app.settings.navigation.config.js
- src/components/settings/notification-web-hooks/WebHookDetails.js
- src/components/settings/notification-web-hooks/WebHookForm.js
- src/components/settings/notification-web-hooks/WebHooksList.js
- src/components/settings/notification-web-hooks/WebHooksSetting.js
- src/components/settings/notification-web-hooks/webhook.service.js
- src/config/admin.config.js
- src/event/event.broadcaster.js
- src/websocket/admin.websocket.js
#70 
아래와 같이 웹 훅을 등록할 수 있음
웹훅을 등록하면 호출할 수 있는 정보를 보여 줌
웹훅을 호출 하면 어드민 화면 우측 상단에 알림이 보여짐
> #70 알림 기능 지원

- src/components/layout/AppLayoutContext.js
> #89 API 호출 시 자동 로딩시 로딩 이미지가 사라지지 않는 오류

- src/components/settings/organization/OrganizationMemberChange.js
- src/components/settings/organization/OrganizationRoleChange.js
> #82 조직에 맴버/역할을 할당 할 때 검색하여 할당할 수 있는 UI로 변경한다

- src/components/settings/access-control/RoleForm.js
- src/components/settings/access-control/RoleList.js
- src/components/settings/member/MemberRoleChange.js
> #83 역할에 권한을 할당할 때 검색하여 여러개를 선택할 수 있는 구조로 UI를 변경한다

- src/components/settings/AppSettings.css
- src/components/settings/AppSettings.js
- src/components/settings/access-control/RoleForm.js
- src/components/settings/access-control/RoleList.js
#91 
레이아웃 깨지는 부분을 올바르게 나오도로 수정함
역할에 할당한 권한이 많을 경우를 대비하여 UI를 접고 펼칠 수 있도록 수정
> #91 역할에 권한을 많이 매핑한 경우 레이아웃 깨지는 문제

- src/components/settings/member/MemberList.js
- src/components/settings/member/member.service.js
> #85 멤버 목록에서 '로그인 유형'과 '멤버 역할'에 필터를 적용한다

- src/components/settings/member/MemberList.js
> #84 멤버를 이름으로 검색할 수 있게 만든다

- src/components/layout/NavigationIcon.js
- src/config/navigation.json
> #105 React 빌드 시 메모리 부족으로 빌드가 되지 않는 오류

- src/components/layout/AppLayoutContext.js
> #107 '잘못된 경로 입니다. 메뉴를 통해 접근해 주세요' 메시지 문제 해결하기

- src/components/layout/AppLayoutContext.js
- src/components/layout/LoginInfo.js
> #110 로그아웃 후 다른 계정으로 로그인할 때 이전 계정의 탭이 유지되는 오류

- src/components/layout/Content.js
> #112 여러개의 탭을 연 상태에서 탭을 전환 했을 때 React useEffect가 탭의 갯수 만큼 호출 되는 오류

- src/components/layout/Sider.js
> #114 화면 크기가 작으면 SideNavigationBar가 자동으로 접히는 기능 지원

- src/components/settings/member/MemberList.js
- src/components/settings/member/MemberSetting.js
> #78 멤버 목록 화면에서 상세나 편집으로 이동 후 다시 돌아왔을 때 기존 페이지와 검색 조건, 필터 유지 시키기

- package.json
- src/components/settings/member/MemberApproval.js
- src/components/settings/member/member.service.js
- src/config/admin.config.js
> #104 사이트 멤버 관리자는 신청한 계정을 '승인 거절'하고 싶다.

- src/config/admin.config.js
> #99 권한 추가시 중복되는 경우 '잘못된 요청입니다.'메시지가 뜨는 오류

- craco.config.js
- package.json
- src/App.less
- src/components/layout/Content.js
- src/components/layout/Header.js
- src/components/settings/AppSettings.js
- src/config/theme.config.json
> #121 UI 다크 모드 지원

- Dockerfile
> #129 도커 이미지를 만들기 위한 Dockerfile 추가

- src/components/layout/Sider.js
- src/config/navigation.json
@torouso 아래와 같이 나타납니다. 참조 하세요.
> #124 메뉴 중에서 사용하지 않는 메뉴는 비활성화 할 수 있는 옵션을 제공한다.

- src/components/settings/member/MemberList.js
> #137 사용자의 마지막 로그인 시간을 보고 싶다.

- src/App.js
#139 
@babokim 네트워크 연결이 되지 않는 경우 예를 들면 API 서버에 연결할 수 없는 경우에는 API를 여러번 호출하는 경우 오류 팝업이 여러개 뜰수 있습니다.
App.js 에서 useEffect 가 한번만 호출하도록 수정 했습니다.
useCallback 훅을 쓴 코드가 있는데요. 이건 React 에서 경고창에서 경고하는 내용이라서 추가한 내용입니다.
> #139 에러가 발생하면 오류 알림 팝업이 두번 호출 되는 오류

- src/App.js
> #141 App.js useCallback 사용 코드 리펙토링

- src/auth/member.context.js
> #94 로그인 후 첫 화면(HOME)은 활성화된 메뉴의 첫번째 화면으로 나오게 한다.

- src/components/router/AuthRoute.js
> #145 최초 아이디/패스워드 입력 후 로그인 시 안되고 다시 로그인 하면 되는 오류

- src/components/layout/Content.js
- src/components/layout/LoginInfo.js
- src/components/monitoring/Monitoring.css
- src/components/monitoring/Monitoring.js
- src/components/monitoring/member-access-logs/MemberAccessLogs.js
- src/components/monitoring/member-access-logs/member.access.log.service.js
- src/components/monitoring/monitoring.navigation.config.js
- src/config/admin.config.js
- src/config/axios.configur.js
- src/index.js
- src/logger/member.access.logger.js
> #134 사용자 접근 로그를 기록하고 보여 준다.

- src/components/monitoring/member-access-logs/MemberAccessLogs.js
- src/config/axios.configur.js
- src/logger/member.access.logger.js
> #155 멤버 접근 로그에 API 호출시에는 추가로 응답 HTTP Status Code를 보고 싶다.

- src/components/settings/app.settings.navigation.config.js
- src/components/settings/member-access-logs/MemberAccessLogSetting.js
- src/config/admin.config.js
> #156 사이트 관리자는 로그가 너무 많아지는 것을 막기 위해 멤버 접근 로그의 보관 기간을 설정하고 싶다

- src/auth/auth.service.js
- src/components/login/DoorayLogin.js
- src/components/login/Login.js
- src/components/login/MemberSignUp.js
- src/components/settings/access-control/PermissionForm.js
- src/components/settings/access-control/RoleForm.js
- src/components/settings/access-control/access.control.service.js
- src/components/settings/member/member.service.js
- src/config/admin.config.js
- src/config/axios.configur.js
- src/logger/member.access.logger.js
> #77 API 호출시 HTTP 응답 Status Code가 4XX, 5XX를 개발자가 직접 처리하고 싶다.

- package.json
> #163 npm install 시 오류

- src/components/login/DoorayLogin.js
> #167 두레이로 로그인할 때 서버 오류가 나지 않았음에도 불구하고 서버 오류 메시지를 보여 준다.

- .storybook/main.js
- .storybook/preview.js
- package.json
- src/components/atoms/button/index.js
- src/components/atoms/button/index.stories.js
- src/components/layout/Content.js
> #172 Design Component 개발을 위한 Storybook.js 적용하기

- package.json
- src/components/layout/AppLayout.js
> #174 react-app-version-checker 적용하기

- package.json
- src/config/axios.configur.js
> #178 서버 네트워크 접속이 되지 않을 때 화면이 멈추는 오류

- src/components/layout/Content.js
> #182 URL에 Parameter가 추가된 경우 탭 전환 시 URL Parameter를 유지하지 않음

- src/components/atoms/button-bind/index.js
- src/components/atoms/button-bind/index.stories.js
- src/components/atoms/button-bind/style.less
하나의 Template bind Component 사용과 개별 버튼의 args 분리된 버튼 타입 추가. [추후 목적에 맞게 선택 예정]
Popconfirm / control에 옵션 추가
> #180 새버튼타입

- .storybook/main.js
> #189 Storybook Server 실행 시 WebpackOptionsValidationError

- package.json
> #192 storybook-addon-styled-component-theme 를 devDependencies 로 옮긴다.

- src/components/layout/NavigationIcon.js
- src/components/login/DoorayLogin.js
- src/components/login/Login.js
- src/config/navigation.config.js
- src/config/navigation.json
> #198 접근 제어 메뉴에 권한 설정 추가하기

- src/components/layout/AppLayout.js
- src/components/layout/AppLayoutContext.js
- src/components/layout/Sider.js
- src/config/navigation.config.js
- src/config/navigation.json
> #201 메뉴 컴포넌트 Rendering 시 Warning 해결하기

- src/components/layout/Content.js
> #206 처음 로그인 할 때 열리는 탭을 닫고 다른 탭을 연 상태에서 다시 로그인하면 이전 탭이 보이지 않는 오류

- package.json
- src/components/layout/Content.js
- src/components/layout/LoginInfo.js
- src/components/modules/backdrop/AutoBackdrop.js
- src/components/templates/member/member.service.js
- src/components/templates/organization/organization.service.js
- src/components/templates/settings/access-control/access.control.service.js
> #215 자동 로딩 이미지가 나오지 않는다

- src/components/atoms/button/index.js
- src/components/login/DoorayLogin.js
- src/components/login/MemberSignUp.js
> #203 Modal 컴포넌트 Warning 해결하기

- src/components/templates/access-control/access.control.service.js
- src/components/templates/access-control/permission/PermissionForm.js
- src/components/templates/access-control/permission/PermissionList.js
- src/components/templates/access-control/role/RoleForm.js
- src/components/templates/access-control/role/RoleList.js
- src/components/templates/member/MemberApproval.js
- src/components/templates/member/MemberList.js
- src/components/templates/member/MemberRoleChange.js
- src/components/templates/organization/OrganizationChangeRoles.js
- src/components/templates/organization/Organizations.js
- src/config/navigation.js
- src/pages/router/PageRouter.js
> #220 Ant Design Dropdown 컴포넌트 Warning 해결하기

- src/components/layout/AppLayout.js
- src/components/layout/AppLayoutContentContext.js
> #223 탭 전환 과정에서 이전 페이지가 나타나는 오류

- src/components/templates/access-control/permission/PermissionForm.js
- src/components/templates/access-control/permission/PermissionList.js
- src/components/templates/access-control/role/RoleForm.js
- src/components/templates/access-control/role/RoleList.js
- src/components/templates/member/MemberList.js
- src/components/templates/member/MemberRoleChange.js
- src/components/templates/organization/OrganizationChangeMembers.js
- src/components/templates/organization/OrganizationChangeRoles.js
- src/components/templates/organization/OrganizationForm.js
- src/components/templates/organization/Organizations.js
> #212 상세 화면에서 다른 탭으로 이동하여도 '뒤로 가기' 버튼 클릭할 때 이전 화면(목록)으로 돌아갈 수 있도록 만든다

- src/components/layout/Sider.js
- src/components/login/MemberSignUp.js
- src/components/services/access.control.service.js
- src/components/services/member.service.js
- src/components/services/organization.service.js
- src/components/services/site.service.js
- src/components/settings/app.settings.navigation.config.js
- src/components/templates/access-control/permission/PermissionForm.js
- src/components/templates/access-control/permission/PermissionList.js
- src/components/templates/access-control/role/RoleForm.js
- src/components/templates/access-control/role/RoleList.js
- src/components/templates/member/MemberApproval.js
- src/components/templates/member/MemberList.js
- src/components/templates/member/MemberRoleChange.js
- src/components/templates/organization/OrganizationChangeMembers.js
- src/components/templates/organization/OrganizationChangeRoles.js
- src/components/templates/organization/OrganizationForm.js
- src/components/templates/organization/Organizations.js
- src/components/templates/settings/dooray/DoorayLoginSetting.js
- src/components/templates/settings/google/GoogleWorkspaceLoginSetting.js
- src/config/navigation.js
- src/pages/router/PageRouter.js
> #207 사이트 설정 > 로그인 화면을 사이드 메뉴의 설정 메뉴로 옮긴다

- Dockerfile
- default.conf
> #235 도커로 배포시 페이지를 새로고침하면 404 페이지 나타나는 오류

- src/components/layout/Sider.js
> #231 admin 관리페이지 좌즉 같은 메뉴 클릭시 접기 기능 추가

- src/components/atoms/layout/footer/index.js
- src/components/atoms/layout/footer/index.stories.js
- src/components/atoms/layout/header/index.js
- src/components/atoms/layout/header/index.stories.js
- src/components/layout/AppLayout.js
> #240 Layout Footer를 Admin Design Component로 대체한다

- src/App.test.js
- src/components/layout/Sider.js
- src/config/navigation.config.js
- src/config/navigation.config.test.js
- src/config/navigation.js
> #249 NavigationConfig 단위 테스트 작성하기

- src/event/event.broadcaster.js
- src/event/event.broadcaster.test.js
> #251 event.broadcaster.js 단위 테스트 작성 하기

- .eslintrc.js
- package.json
> #255 ESLint 환경 만들기

- src/event/event.broadcaster.js
> #260 event.broadcaster.test.js esLint 적용

- src/components/templates/access-control/permission/PermissionForm.js
- src/components/templates/access-control/permission/PermissionList.js
- src/components/templates/access-control/role/RoleForm.js
- src/components/templates/access-control/role/RoleList.js
- src/components/templates/login/MemberSignUp.js
- src/components/templates/member/MemberApproval.js
- src/components/templates/member/MemberList.js
- src/components/templates/member/MemberRoleChange.js
- src/components/templates/organization/OrganizationChangeMembers.js
- src/components/templates/organization/OrganizationChangeRoles.js
- src/components/templates/organization/OrganizationForm.js
- src/components/templates/organization/Organizations.js
- src/components/templates/webhook/notification-web-hooks/NotificationWebHookCallSampleDetails.js
- src/components/templates/webhook/notification-web-hooks/NotificationWebHookForm.js
- src/components/templates/webhook/notification-web-hooks/NotificationWebHookList.js
- src/services/access.control.service.js
- src/services/member.service.js
- src/services/organization.service.js
- src/services/site.service.js
- src/services/webhook.service.js
#262 
/* eslint-disable arrow-body-style */ -- ESLint 의 경우 arrow function 사용 시 body 가 한 줄로 되어 있을 때 코드를 한 줄로 사용하기를 권장
/* eslint-disable quotes */ ESLint 의 경우 모든 스트링에 싱글 쿼테이션 사용 권장
/* eslint-disable object-shorthand */ ESLint 의 경우 key : value 형태에서 둘의 이름이 같을 때 해당 형태가 아닌 한개의 이름만 사용하기를 권장
/* eslint-disable class-methods-use-this */ Class 안에 this 를 사용하기를 권장
/* eslint-disable import/prefer-default-export */ Single export ( 하나의 값만 내보내는 export) 사용 시 default export 사용 권장
> #262 src/services 디렉토리의 js 파일에 ESLint 를 적용

- src/event/event.broadcaster.js
#260 에서 적용된 ESLint 수정사항 발견 ,
#265 수정
> #265 event.broadcaster.js 에 적용된 ESLint 수정

- src/components/templates/access-control/permission/PermissionList.js
- src/components/templates/access-control/permission/PermissionList.test.js
- src/setupTests.js
> #263 권한 목록 React Component의 단위 테스트 케이스를 만든다.

- .eslintrc.js
- src/components/templates/login/DoorayLogin.js
- src/components/templates/login/Login.js
- src/components/templates/login/MemberSignUp.js
- src/components/templates/login/OAuthLoginResult.js
@YooYoungmo 수정사항 반영하여서 PR 재요청 드립니다.
> #268 src/components/templates/login 디렉토리의 js 파일에 ESLint 를 적용한다.

- src/components/templates/profile/Profile.js
- src/components/templates/profile/Profile.test.js
> #279 Profile React Component의 Jest 단위 테스트를 작성한다.

- src/components/templates/member/MemberApproval.js
- src/components/templates/member/MemberList.js
- src/components/templates/member/MemberRoleChange.js
> #278 member 디렉토리 React Compoent에 ESLint 를 적용한다

- src/components/layout/LoginInfo.js
- src/components/templates/profile/Profile.test.js
> #283 Profile.test.js에 이벤트 관련 test case를 추가한다.

- package.json
- src/components/templates/access-control/permission/PermissionList.test.js
@YooYoungmo 님.
조건 1 "url parameter 에 따라" 완료했습니다.
테스트 데이터를 전체적으로 많이 쓸 것 같아 전역으로 만들었는데요
이런식으로 진행하여도 문제 없을까요? 리뷰 부탁드립니다.
> #271 권한 목록 React Component의 테이블 랜더링 조건별 테스트 케이스 작성한다.

- src/components/templates/access-control/permission/PermissionList.test.js
#288 
@YooYoungmo 님. PR 요청 드립니다.
> #288 권한 목록 React component의 권한 이름 필터링에 따른 테이블 렌더링 테스트 케이스를 작성한다.
